version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: project_capstone
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network_microservice

  backend:
    image: jarntae/backend:3.0.0
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./Backend/.env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - network_microservice
      - network_webapp
  
  model:
    build:
      context: ./Backend/Model
      dockerfile: Dockerfile
    container_name: model
    ports:
      - "8001:8001"
    depends_on:
      - backend
    environment:
      - MODEL_SA_JSON=/app/ServiceAcc/CapStoneKEY.json
    volumes:
      - ./Backend/Model/ServiceAcc:/app/ServiceAcc:ro
    networks:
      - network_microservice

  nginx:
    # image: jarntae/nginx:3.0.0
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - network_webapp
      - network_microservice

networks:
  network_webapp:
  network_microservice:

volumes:
  postgres_data: